# Generated by Django 4.1.2 on 2022-10-18 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 19, 8, 29, 51, 24120, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
